exports.up = function (knex) {
  return knex.schema.createTable('sheet', (table) => {
    table.increments('id').primary();
    table
      .integer('user_id')
      .unsigned()
      .notNullable()
      .references('id')
      .inTable('user')
      .onUpdate('CASCADE')
      .onDelete('CASCADE');
    table
      .integer('session_id')
      .unsigned()
      .notNullable()
      .references('id')
      .inTable('user')
      .onUpdate('CASCADE')
      .onDelete('CASCADE');
    table.timestamps(true, true);
    table.string('c_name').notNullable();
    table.string('class').notNullable();
    table.string('level').notNullable();
    table.string('background').notNullable();
    table.string('p_name').notNullable();
    table.string('race').notNullable();
    table.string('aligment').notNullable();
    table.integer('str').notNullable();
    table.integer('dex').notNullable();
    table.integer('con').notNullable();
    table.integer('wis').notNullable();
    table.integer('int').notNullable();
    table.integer('cha').notNullable();
    table.integer('save_str').notNullable();
    table.integer('save_dex').notNullable();
    table.integer('save_con').notNullable();
    table.integer('save_wis').notNullable();
    table.integer('save_int').notNullable();
    table.integer('save_cha').notNullable();
    table.integer('s_acrobatics').notNullable();
    table.integer('s_animal_h').notNullable();
    table.integer('s_arcana').notNullable();
    table.integer('s_athletics').notNullable();
    table.integer('s_seception').notNullable();
    table.integer('s_history').notNullable();
    table.integer('s_insight').notNullable();
    table.integer('s_intimidation').notNullable();
    table.integer('s_investigation').notNullable();
    table.integer('s_medicine').notNullable();
    table.integer('s_nature').notNullable();
    table.integer('s_perception').notNullable();
    table.integer('s_performance').notNullable();
    table.integer('s_persuation').notNullable();
    table.integer('s_religion').notNullable();
    table.integer('s_slightOfHand').notNullable();
    table.integer('s_stealth').notNullable();
    table.integer('s_survival').notNullable();
    table.integer('passive_perception');
    table.string('lang_and_profiency').notNullable();
    table.string('armor_class').notNullable();
    table.integer('initiative').notNullable();
    table.string('speed').notNullable();
    table.integer('health_points').notNullable();
    table.integer('temp_health_points');
    table.string('attacks').notNullable();
    table.string('equipment').notNullable();
    table.string('personality').notNullable();
    table.string('ideals').notNullable();
    table.string('bonds').notNullable();
    table.string('flaws').notNullable();
    table.string('traits').notNullable();
  });
};

exports.down = function (knex) {
  return knex.schema.dropTable('sheet');
};
